master composer: install composer programatically

diff --git a/setup/templates/php/Dockerfile b/setup/templates/php/Dockerfile
--- a/setup/templates/php/Dockerfile
+++ b/setup/templates/php/Dockerfile
@@ -2,8 +2,10 @@ FROM debian:11
 
 RUN apt-get update && apt-get install -y vim curl zip unzip git php7.4-cli php7.4-zip php7.4-dom php7.4-mbstring php7.4-json docker.io docker-compose
 
+RUN EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
 RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
-RUN php -r "if (hash_file('sha384', 'composer-setup.php') === 'e21205b207c3ff031906575712edab6f13eb0b361f2085f1f1237b7126d785e826a450292b6cfd1d64d92e6563bbde02') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
+RUN ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
+RUN if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]; then >&2 echo 'ERROR: Invalid installer checksum'; exit 1; fi
 RUN php composer-setup.php
 RUN php -r "unlink('composer-setup.php');"
 RUN mv composer.phar /usr/local/bin/composer
